/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Business.DB4OUtil.DB4OUtil;
import Business.Ecosystem.Ecosystem;
import Business.Manufacturer.Manufacturer;
import Business.Role.EnterpriseAdmin;
import Business.Role.Volunteer;
import Business.Role.clinicProvider;
import Business.enterprise.Enterprise;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tendusmac
 */
public class EnterpriseAdminWorkArea extends javax.swing.JFrame {

    /**
     * Creates new form EnterpriseAdminWorkArea
     */
    Ecosystem ecoSystem = Ecosystem.getInstance();
    DB4OUtil dB40Util = DB4OUtil.getInstance();
    EnterpriseAdmin loggedInUser;
    Manufacturer selectedManObj;
    clinicProvider provider;

    public EnterpriseAdminWorkArea(EnterpriseAdmin enterpriseAdmin) {
        initComponents();
        TableFilling3();
        TableFilling4();
        fillenter();
        jPanel26.setBackground(new Color(255, 255, 255, 90));
        workPanel8.setBackground(new Color(255, 255, 255, 100));
        this.loggedInUser = enterpriseAdmin;
         firstname6.setName("Firstname");
                    lastname6.setName("Lastname");
                    email8.setName("EmailId");
                    //dob2.setDate(null);
                    phone8.setName("Phone");
                    //gender8.setSelectedItem(null);
                    //location8.setText("");
        
        welcome.setText("Hello "+loggedInUser.getFirstName()+" "+loggedInUser.getLastName()+"!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        manufacturername = new javax.swing.JTextField();
        emailid = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        Create1 = new javax.swing.JButton();
        Enterprise = new javax.swing.JLabel();
        enterpriselist = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        manufacturertable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Create2 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        clinicprovider = new javax.swing.JPanel();
        workPanel8 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        firstname6 = new javax.swing.JTextField();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        lastname6 = new javax.swing.JTextField();
        email8 = new javax.swing.JTextField();
        phone8 = new javax.swing.JTextField();
        jLabel98 = new javax.swing.JLabel();
        gender8 = new javax.swing.JComboBox<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jLabel99 = new javax.swing.JLabel();
        location8 = new javax.swing.JTextField();
        password8 = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        dob2 = new com.toedter.calendar.JDateChooser();
        create8 = new javax.swing.JButton();
        update6 = new javax.swing.JButton();
        delete6 = new javax.swing.JButton();
        select5 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jLabel103 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel2.setBackground(new java.awt.Color(165, 218, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Manufacturer Name");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Email id");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Password");

        manufacturername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturernameActionPerformed(evt);
            }
        });

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        Create1.setBackground(new java.awt.Color(0, 102, 150));
        Create1.setForeground(new java.awt.Color(255, 255, 255));
        Create1.setText("Create");
        Create1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create1ActionPerformed(evt);
            }
        });

        Enterprise.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Enterprise.setText("Enterprise");

        enterpriselist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriselistActionPerformed(evt);
            }
        });

        manufacturertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ManufacturerId", "ManufacturerName", "Email", "Enterprise"
            }
        ));
        jScrollPane3.setViewportView(manufacturertable);

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Create Manufacturer");

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 102, 150));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Select");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Create2.setBackground(new java.awt.Color(0, 102, 150));
        Create2.setForeground(new java.awt.Color(255, 255, 255));
        Create2.setText("Update Password");
        Create2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create2ActionPerformed(evt);
            }
        });

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/previous (4).png"))); // NOI18N
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        welcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome.setText("First Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Enterprise)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel5))
                                            .addGap(31, 31, 31)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(enterpriselist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(Create1)
                                            .addGap(33, 33, 33))
                                        .addComponent(Create2)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(manufacturername, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jButton6)
                        .addGap(142, 142, 142)
                        .addComponent(jButton5)
                        .addGap(155, 155, 155)
                        .addComponent(jButton4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(welcome))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manufacturername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Create2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enterpriselist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Enterprise))
                        .addGap(49, 49, 49)
                        .addComponent(Create1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Manufacturer", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        clinicprovider.setLayout(null);

        jLabel93.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel93.setText("First Name");

        jLabel94.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel94.setText("Date of Birth");

        jLabel95.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel95.setText("Last Name");

        jLabel96.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel96.setText("Phone Number");

        jLabel97.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel97.setText("Email ID");

        email8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email8ActionPerformed(evt);
            }
        });

        phone8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone8ActionPerformed(evt);
            }
        });

        jLabel98.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel98.setText("Gender");

        gender8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        gender8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender8ActionPerformed(evt);
            }
        });

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last name", "Date of Birth", "Gender", "Email ID", "Phone Number", "Password"
            }
        ));
        jScrollPane12.setViewportView(jTable10);

        jLabel99.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel99.setText("Password");

        location8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location8ActionPerformed(evt);
            }
        });

        password8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password8ActionPerformed(evt);
            }
        });

        jLabel101.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel101.setText("Location");

        create8.setBackground(new java.awt.Color(43, 89, 232));
        create8.setForeground(new java.awt.Color(255, 255, 255));
        create8.setText("Create");
        create8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create8ActionPerformed(evt);
            }
        });

        update6.setText("Update");
        update6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update6ActionPerformed(evt);
            }
        });

        delete6.setBackground(new java.awt.Color(255, 102, 102));
        delete6.setForeground(new java.awt.Color(255, 255, 255));
        delete6.setText("Delete");
        delete6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete6ActionPerformed(evt);
            }
        });

        select5.setBackground(new java.awt.Color(153, 153, 153));
        select5.setForeground(new java.awt.Color(255, 255, 255));
        select5.setText("Select");
        select5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select5ActionPerformed(evt);
            }
        });

        jButton30.setText("Set Location");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setText("Update");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton41.setText("Update");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout workPanel8Layout = new javax.swing.GroupLayout(workPanel8);
        workPanel8.setLayout(workPanel8Layout);
        workPanel8Layout.setHorizontalGroup(
            workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanel8Layout.createSequentialGroup()
                .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workPanel8Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(create8))
                    .addGroup(workPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(workPanel8Layout.createSequentialGroup()
                                .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phone8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, workPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel97, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(email8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, workPanel8Layout.createSequentialGroup()
                                    .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(location8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, workPanel8Layout.createSequentialGroup()
                                            .addGap(119, 119, 119)
                                            .addComponent(password8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(workPanel8Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(workPanel8Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton30))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, workPanel8Layout.createSequentialGroup()
                                    .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel98, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)
                                    .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(gender8, 0, 173, Short.MAX_VALUE)
                                        .addComponent(dob2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, workPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lastname6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, workPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(firstname6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workPanel8Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(select5)
                        .addGap(133, 133, 133)
                        .addComponent(update6)
                        .addGap(140, 140, 140)
                        .addComponent(delete6))
                    .addGroup(workPanel8Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        workPanel8Layout.setVerticalGroup(
            workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanel8Layout.createSequentialGroup()
                .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(workPanel8Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel93)
                            .addComponent(firstname6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel95)
                            .addComponent(lastname6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel94)
                            .addGroup(workPanel8Layout.createSequentialGroup()
                                .addComponent(dob2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(workPanel8Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel98))
                            .addGroup(workPanel8Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(gender8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel97)
                            .addComponent(email8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phone8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel96))
                        .addGap(28, 28, 28)
                        .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel99)
                            .addComponent(password8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton31))
                        .addGap(34, 34, 34)
                        .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(location8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel101)
                            .addComponent(jButton30))))
                .addComponent(jButton41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create8)
                    .addComponent(update6)
                    .addComponent(delete6)
                    .addComponent(select5))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        clinicprovider.add(workPanel8);
        workPanel8.setBounds(0, -30, 1400, 700);

        jPanel26.setLayout(new javax.swing.OverlayLayout(jPanel26));

        jLabel103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/10976.jpg"))); // NOI18N
        jLabel103.setMaximumSize(new java.awt.Dimension(1200, 700));
        jLabel103.setMinimumSize(new java.awt.Dimension(1200, 700));
        jLabel103.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel26.add(jLabel103);

        clinicprovider.add(jPanel26);
        jPanel26.setBounds(0, 0, 1200, 700);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setFocusable(false);
        jPanel27.setMaximumSize(new java.awt.Dimension(1200, 700));
        jPanel27.setMinimumSize(new java.awt.Dimension(1200, 700));
        jPanel27.setLayout(new javax.swing.OverlayLayout(jPanel27));
        clinicprovider.add(jPanel27);
        jPanel27.setBounds(0, 0, 1200, 700);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1202, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(clinicprovider, javax.swing.GroupLayout.DEFAULT_SIZE, 1202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(clinicprovider, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clinic Provider", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Create1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create1ActionPerformed
        // TODO add your handling code here:
        if(manufacturername.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Manufacturer Name is mandatory!");
        } else if(emailid.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Manufacturer Email is mandatory!");
        } else if(password.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Manufacturer Password is mandatory!");
        } else if(enterpriselist.getSelectedItem().toString().isBlank()){
            JOptionPane.showMessageDialog(this, "Select an Enterprise");           
        } else{
            Manufacturer manObj = new Manufacturer(manufacturername.getText(), emailid.getText(), loggedInUser.getEnterprise(), null, password.getText());
            TableFilling3();
            JOptionPane.showMessageDialog(this, "Manufacturer Creation Successful!"); 
            manufacturername.setText("");
            emailid.setText("");
            password.setText("");
            enterpriselist.setSelectedItem(null);
        }
    }//GEN-LAST:event_Create1ActionPerformed

    private void manufacturernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int s = manufacturertable.getSelectedRow();
        if (s == -1) {
            JOptionPane.showMessageDialog(this, " select Manufacturer");
        } else {
            for (Manufacturer ma : ecoSystem.getManufacturerCatalog().getManufacturerList()) {

                if (ma.getManufacturerId().equals(manufacturertable.getValueAt(s, 0))) {
                    ecoSystem.getPasswordManager().removePassword("Manufacturer", ma.getEmailId());
                    ecoSystem.getManufacturerCatalog().removeManufacturer(ma);
                    TableFilling3();
                    JOptionPane.showMessageDialog(this, "Manufacturer Deleted");
                    break;
                }
            }

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Enterprise d = null;
        int s = manufacturertable.getSelectedRow();
        if (s == -1) {
            JOptionPane.showMessageDialog(this, "Select Manufacturer");
        }
        for (Enterprise e : ecoSystem.getEnterpriseDirectory().getEnterprisedirectory()) {
            if (e.getCompanyName().equals(enterpriselist.getSelectedItem().toString())) {
                d = e;
                break;
            }

        }
        for (Manufacturer mu : ecoSystem.getManufacturerCatalog().getManufacturerList()) {
            if (mu.getManufacturerId().equals(manufacturertable.getValueAt(s, 0).toString())) {

                mu.setManufacturerName(manufacturername.getText());
                mu.setEmailId(emailid.getText());
                mu.setEnterprise(d);
                TableFilling3();
                JOptionPane.showMessageDialog(this, "Manufacturer Updated Successfully!");
                manufacturername.setText("");
                emailid.setText("");
                password.setText("");
                enterpriselist.setSelectedItem(null);
            
                
            }
        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int s = manufacturertable.getSelectedRow();
        if (s == -1) {
            JOptionPane.showMessageDialog(this, "Select Manufacturer");
        }
        for (Manufacturer mu : ecoSystem.getManufacturerCatalog().getManufacturerList()) {
            if (mu.getManufacturerId().equals(manufacturertable.getValueAt(s, 0).toString())) {

                manufacturername.setText(mu.getManufacturerName());
                emailid.setText(mu.getEmailId());
                enterpriselist.setSelectedItem(mu.getManufacturerName());

            }

        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void enterpriselistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriselistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriselistActionPerformed

    private void Create2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create2ActionPerformed
        // TODO add your handling code here:
        if(manufacturertable.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Select a Manufacturer");
        }
        else{
            for(Manufacturer manObj:ecoSystem.getManufacturerCatalog().getManufacturerList()){
                if(manObj.getManufacturerId().equalsIgnoreCase(manufacturertable.getValueAt(manufacturertable.getSelectedRow(),0).toString())){
                    manObj.setPassword(password.getText());
                    TableFilling3();
                    JOptionPane.showMessageDialog(this, "Password Updated");
                  
                    manufacturername.setText("");
                    emailid.setText("");
                    password.setText("");
                    enterpriselist.setSelectedItem(null);
                    break;
                }
            }
        }
    }//GEN-LAST:event_Create2ActionPerformed

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:

        dB40Util.storeSystem(Ecosystem.getInstance());
        Login mf = new Login();
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel33MouseClicked

    private void email8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email8ActionPerformed

    private void phone8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone8ActionPerformed

    private void gender8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender8ActionPerformed

    private void location8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_location8ActionPerformed

    private void password8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password8ActionPerformed

    private void create8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create8ActionPerformed
        // TODO add your handling code here:
        boolean validated = false;
        boolean validatedOtherFields = false;
        String selectedGender = gender8.getSelectedItem().toString();

        JDateChooser strtDt = dob2;
        if (strtDt != null) {
            validatedOtherFields = true;
        } else {
            JOptionPane.showMessageDialog(this, "All Fields are Mandatory!");
        }
        JTextField[] VARIABLE_CONSTANTS = {firstname6, lastname6, email8, phone8};
        for (JTextField field : VARIABLE_CONSTANTS) {
            if (!validateData(field)) {
                validated = false;
                break;
            } else {
                validated = true;
                System.out.println("Validated");
            }
        }

        if (validated && validatedOtherFields) {

            clinicProvider volunteer = new clinicProvider(password8.getText(), firstname6.getText(), lastname6.getText(), dob2.getDate(), email8.getText(), gender8.getSelectedItem().toString(), Long.parseLong(phone8.getText()), location8.getText());
            TableFilling4();
                    firstname6.setText("");
                    lastname6.setText("");
                    email8.setText("");
                    dob2.setDate(null);
                    phone8.setText("");
                    gender8.setSelectedItem(null);
                    location8.setText("");
                    JOptionPane.showMessageDialog(this, "clinic provider Created!");
        } else {
            JOptionPane.showMessageDialog(this, "All Fields are Mandatory!");
        }
    }

    public boolean validateData(JComponent input) {
        String name = input.getName();
        String errorMsg = "";
        boolean raiseError = false;
        String text = ((JTextField) input).getText().trim();
        if (text == null || text.isEmpty()) {
            raiseError = true;
            errorMsg = String.format("Please enter a value. The value for %s cannot be empty", name);
        } else {
            switch (name) {
                case "FirstName":
                    if (!text.matches("^[a-zA-z ]*$")) {
                        raiseError = true;
                        errorMsg = String.format("Please enter valid values for %s", name);
                    }
                    break;
                case "LastName":
                    if (!text.matches("^[a-zA-z ]*$")) {
                        raiseError = true;
                        errorMsg = String.format("Please enter valid values for %s", name);
                    }
                    break;
                case "Phone":
                    if (!text.matches("^[0-9]{10}")) {
                        raiseError = true;
                        errorMsg = String.format("Please enter a valid %s", name);
                    }
                    break;
                case "EmailId":
                    System.out.print(text);
                    if (!ecoSystem.getPasswordManager().isUsernameAvailable(text, "Clinic Provider")) {
                        raiseError = true;
                        errorMsg = String.format("Email Id already exists, please enter a valid mail Id", name);
                        break;
                    }
                    if (!text.matches("^(.+)@(.+)$")) {
                        raiseError = true;
                        errorMsg = String.format("Please enter a valid %s", name);
                    }
                    break;

                default:
                    break;
            }
        }
        if (raiseError) {
            JOptionPane.showMessageDialog(this, errorMsg);
            return false;
        }
        return true;
        
        
    }//GEN-LAST:event_create8ActionPerformed

    private void update6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update6ActionPerformed
        // TODO add your handling code here:
        int s = jTable10.getSelectedRow();
        if (s == -1) {
            JOptionPane.showMessageDialog(this, "Select Clinic Provider");
        } else {
            for (clinicProvider vi : ecoSystem.getClinicProviderDirectory().getClinicproviderdirectory()) {
                if (vi.getClinicproviderId().equals(jTable10.getValueAt(s, 0).toString())) {

                    vi.setFirstName(firstname6.getText());
                    vi.setLastName(lastname6.getText());
                    vi.setDateOfBirth(dob2.getDate());
//                    vi.setEmailId(email.getText());
                    vi.setPhoneNumber(Long.valueOf(phone8.getText()));
                    vi.setGender(gender8.getSelectedItem().toString());
                    vi.setLocation(location8.getText());
                    TableFilling4();
                    firstname6.setText("");
                    lastname6.setText("");
                    email8.setText("");
                    dob2.setDate(null);
                    phone8.setText("");
                    gender8.setSelectedItem(null);
                    location8.setText("");
                    JOptionPane.showMessageDialog(this, "Clinic provider Updated");
                    break;

                }
            }

        }
        
        
        
    }//GEN-LAST:event_update6ActionPerformed

    private void delete6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete6ActionPerformed
        // TODO add your handling code here:
        
        
        int s = jTable10.getSelectedRow();
        if (s == -1) {
            JOptionPane.showMessageDialog(this, "Select Clinic Provider");
        } else {
            for (clinicProvider vi : ecoSystem.getClinicProviderDirectory().getClinicproviderdirectory()) {
                if (vi.getClinicproviderId().equals(jTable10.getValueAt(s, 0).toString())) {
                    ecoSystem.getPasswordManager().removePassword("Clinic Provider", vi.getEmailId());
                    ecoSystem.getClinicProviderDirectory().getClinicproviderdirectory().remove(vi);
                    TableFilling4();
                    JOptionPane.showMessageDialog(this, "clinic provider Deleted!");
                    break;
                }

            }
        }
    }//GEN-LAST:event_delete6ActionPerformed

    private void select5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select5ActionPerformed
        // TODO add your handling code here:
        
        int s = jTable10.getSelectedRow();
        if (s == -1) {
            JOptionPane.showMessageDialog(this, "Please select clinic provider");
        } else {
            for (clinicProvider vi : ecoSystem.getClinicProviderDirectory().getClinicproviderdirectory()) {
                if (vi.getClinicproviderId().equals(jTable10.getValueAt(s, 0).toString())) {
                    provider = vi;

                    firstname6.setText(vi.getFirstName());
                    lastname6.setText(vi.getLastName());
                    dob2.setDate(vi.getDateOfBirth());
                    gender8.setSelectedItem(vi.getGender());
                    email8.setText(vi.getEmailId());
                    phone8.setText(vi.getPhoneNumber() + "");
                    password8.setText("");
                    location8.setText(vi.getLocation());
                }

            }
        }
    }//GEN-LAST:event_select5ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        if (password8.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Password Cannot be empty");
        } else {
            for (clinicProvider pObj : ecoSystem.getClinicProviderDirectory().getClinicproviderdirectory()) {
                
                if (pObj.getClinicproviderId().equals(provider.getClinicproviderId())) {
                    pObj.setPassword(password.getText());
                    JOptionPane.showMessageDialog(this, "clinic provider Password Updated");
                    break;
                }
            }
        }
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        
         Location locobj = new Location();
        locobj.setVisible(true);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
        location8.setText(ecoSystem.getgMapsLocation().getLatitude() + "," + ecoSystem.getgMapsLocation().getLongitude());
    }//GEN-LAST:event_jButton41ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EnterpriseAdminWorkAreaOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EnterpriseAdminWorkAreaOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EnterpriseAdminWorkAreaOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EnterpriseAdminWorkAreaOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EnterpriseAdminWorkAreaOld().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create1;
    private javax.swing.JButton Create2;
    private javax.swing.JLabel Enterprise;
    private javax.swing.JPanel clinicprovider;
    private javax.swing.JButton create8;
    private javax.swing.JButton delete6;
    private com.toedter.calendar.JDateChooser dob2;
    private javax.swing.JTextField email8;
    private javax.swing.JTextField emailid;
    private javax.swing.JComboBox<String> enterpriselist;
    private javax.swing.JTextField firstname6;
    private javax.swing.JComboBox<String> gender8;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTextField lastname6;
    private javax.swing.JTextField location8;
    private javax.swing.JTextField manufacturername;
    private javax.swing.JTable manufacturertable;
    private javax.swing.JTextField password;
    private javax.swing.JTextField password8;
    private javax.swing.JTextField phone8;
    private javax.swing.JButton select5;
    private javax.swing.JButton update6;
    private javax.swing.JLabel welcome;
    private javax.swing.JPanel workPanel8;
    // End of variables declaration//GEN-END:variables

    private void TableFilling3() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("MMM dd, yyyy");
        DefaultTableModel model = (DefaultTableModel) manufacturertable.getModel();
        model.setRowCount(0);

        for (Manufacturer ent : ecoSystem.getManufacturerCatalog().getManufacturerList()) {

            Object[] row = new Object[4];
            row[0] = ent.getManufacturerId();
            row[1] = ent.getManufacturerName();
            row[2] = ent.getEmailId();
            row[3] = ent.getEnterprise().getCompanyName();

            model.addRow(row);

        }

    }

    private void fillenter() {

        ArrayList<String> vaccineList = new ArrayList<String>();
        for (Enterprise c : ecoSystem.getEnterpriseDirectory().getEnterprisedirectory()) {
            vaccineList.add(c.getCompanyName());
            System.out.print(c.getCompanyName());
        }
        DefaultComboBoxModel vaccineModelList = new DefaultComboBoxModel(vaccineList.toArray());
        enterpriselist.setModel(vaccineModelList);

    }

    private void TableFilling4() {
       SimpleDateFormat dateFormat = new SimpleDateFormat("MMM dd, yyyy");
        DefaultTableModel model = (DefaultTableModel) jTable10.getModel();
        model.setRowCount(0);

        for (clinicProvider ent : ecoSystem.getClinicProviderDirectory().getClinicproviderdirectory()) {

            Object[] row = new Object[10];
            row[0] = ent.getClinicproviderId();
            row[1] = ent.getFirstName();
            row[2] = ent.getLastName();
            row[4] = ent.getGender();
            row[3]=dateFormat.format(ent.getDateOfBirth());
            row[5]=ent.getEmailId();
            row[6]=ent.getPhoneNumber();
            

            model.addRow(row);

        }
    }
}
